"""Initial migration

Revision ID: e7d0dd8895c1
Revises: 
Create Date: 2026-01-31 18:14:34.613202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d0dd8895c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_authentications',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_url', sa.Text(), nullable=False),
    sa.Column('delivery_target', sa.String(length=255), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('behaviour_logs', sa.UUID(), nullable=True),
    sa.Column('expiry_seconds', sa.Integer(), nullable=False),
    sa.Column('code_len', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_otp_authentications_delivery_target'), 'otp_authentications', ['delivery_target'], unique=False)
    op.create_index(op.f('ix_otp_authentications_expired_at'), 'otp_authentications', ['expired_at'], unique=False)
    op.create_index(op.f('ix_otp_authentications_merchant_id'), 'otp_authentications', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_otp_authentications_otp_code'), 'otp_authentications', ['otp_code'], unique=False)
    op.create_index(op.f('ix_otp_authentications_purpose'), 'otp_authentications', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_authentications_user_id'), 'otp_authentications', ['user_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_log_type'), 'system_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('metadata_user_agent', sa.Text(), nullable=False),
    sa.Column('metadata_ip_address', sa.String(length=45), nullable=False),
    sa.Column('metadata_devices_width', sa.Integer(), nullable=False),
    sa.Column('metadata_devices_length', sa.Integer(), nullable=False),
    sa.Column('metadata_region', sa.String(length=10), nullable=False),
    sa.Column('metadata_lang', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_user_sessions_active_token'), 'user_sessions', ['active_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_device_fingerprint'), 'user_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_user_sessions_expiry'), 'user_sessions', ['expiry'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('register_geolocation', sa.String(length=255), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('primary_contact', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('secret_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('actived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expiry'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_fingerprint'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_active_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_otp_authentications_user_id'), table_name='otp_authentications')
    op.drop_index(op.f('ix_otp_authentications_purpose'), table_name='otp_authentications')
    op.drop_index(op.f('ix_otp_authentications_otp_code'), table_name='otp_authentications')
    op.drop_index(op.f('ix_otp_authentications_merchant_id'), table_name='otp_authentications')
    op.drop_index(op.f('ix_otp_authentications_expired_at'), table_name='otp_authentications')
    op.drop_index(op.f('ix_otp_authentications_delivery_target'), table_name='otp_authentications')
    op.drop_table('otp_authentications')
    # ### end Alembic commands ###
